#!/bin/bash

FSTAB=$1
OUT=$2
DEVICE=$3
DEFCONFIG=$4
SOURCE=$PWD
UPDATER=$OUT/obj/EXECUTABLES/updater_intermediates/updater

LINENUMBER=`sed -n "/\/recovery/ =" $FSTAB | head -1`
LINE=`sed -n "${LINENUMBER}p" $FSTAB`
stringarray=(${LINE})
recoverypartition=${stringarray[2]}
partition_type=${stringarray[1]}
#KERNELVERSION=`sed -n -e "/CONFIG_LOCALVERSION/s/^.*=//p" $4`
SYSTEMNUMBER=`sed -n '/\/system/ =' $FSTAB`
SYSTEMLINE=`sed -n "${SYSTEMNUMBER}p" $FSTAB`
systemarray=(${SYSTEMLINE})
systemtype=${systemarray[1]}
systemmount=${systemarray[2]}

#rm -r $OUT/*recovery*

if [ ! -f "$UPDATER" ]
then
    make updater &>> /dev/null
fi
if [ ! -f "${ANDROID_HOST_OUT}/framework/signapk.jar" ]
then
    make signapk &>> /dev/null
fi

RECOVERY_VERSION=Devil-$DEVICE-fake-flash-recovery

#rm $OUT/$RECOVERY_VERSION
ZIP_DIR=$OUT/$RECOVERY_VERSION
mkdir $ZIP_DIR

# Make the updater-script
UPDATER_DIR=$ZIP_DIR/META-INF/com/google/android
mkdir -p $UPDATER_DIR
cp $OUT/obj/EXECUTABLES/updater_intermediates/updater $UPDATER_DIR/update-binary
echo 'ui_print("Installing Devil Fake-flash Recovery...");' > $UPDATER_DIR/updater-script

echo '       delete_recursive("/sbin");' >> $UPDATER_DIR/updater-script
echo '       delete_recursive("/res");' >> $UPDATER_DIR/updater-script
echo '       delete_recursive("/etc");' >> $UPDATER_DIR/updater-script
echo 'package_extract_dir("etc", "/etc");' >> $UPDATER_DIR/updater-script
echo 'package_extract_dir("sbin", "/sbin");' >> $UPDATER_DIR/updater-script
echo 'package_extract_dir("res", "/res");' >> $UPDATER_DIR/updater-script

# Copy the recovery files
cp -r $OUT/recovery/root/etc $ZIP_DIR/
#cp -r $OUT/recovery/root/sbin $ZIP_DIR/
mkdir -p $ZIP_DIR/sbin
for file in $OUT/recovery/root/sbin/*
do
    filename=$(basename $file)
  if [ ! -h $file ]; then
    cp $OUT/recovery/root/sbin/$filename $ZIP_DIR/sbin/
  else
    symlink_target=$(readlink $file)
    echo "symlink("'"'$symlink_target'"'", "'"'/sbin/$filename'"'");" >> $UPDATER_DIR/updater-script
  fi
done
cp -r $OUT/recovery/root/res $ZIP_DIR/

echo 'set_perm_recursive(0, 2000, 0755, 0755, "/sbin");' >> $UPDATER_DIR/updater-script
echo 'run_program("/sbin/killrecovery.sh");' >> $UPDATER_DIR/updater-script

#zip package
cd $ZIP_DIR
zip -qr ../$RECOVERY_VERSION.zip ./
cd $OUT
rm -rf $ZIP_DIR

#sign package
java -jar ${ANDROID_HOST_OUT}/framework/signapk.jar ${SOURCE}/build/target/product/security/testkey.x509.pem ${SOURCE}/build/target/product/security/testkey.pk8 $RECOVERY_VERSION.zip $RECOVERY_VERSION-signed.zip
rm ./$RECOVERY_VERSION.zip
md5sum $RECOVERY_VERSION-signed.zip
cd $SOURCE
