#!/bin/bash

FSTAB=$1
OUT=$2
DEVICE=$3
DEFCONFIG=$4
SOURCE=$PWD
UPDATER=$OUT/obj/EXECUTABLES/updater_intermediates/updater

#rm $OUT/$RECOVERY_VERSION
RECOVERY_VERSION=Devil-$DEVICE-recovery
ZIP_DIR=$OUT/$RECOVERY_VERSION
mkdir -p $ZIP_DIR

LINENUMBER=`sed -n "/\/recovery/ =" $FSTAB | head -1`
LINE=`sed -n "${LINENUMBER}p" $FSTAB`
stringarray=(${LINE})
recoverypartition=${stringarray[2]}
partition_type=${stringarray[1]}
KERNELVERSION=`sed -n -e "/CONFIG_LOCALVERSION/s/^.*=//p" $4`
TMPFSTAB=$ZIP_DIR/tmp_fstab

sed "s/system)//g" $FSTAB > $TMPFSTAB

SYSTEMNUMBER=`sed -n '/\/system/ =' $TMPFSTAB`
SYSTEMLINE=`sed -n "${SYSTEMNUMBER}p" $TMPFSTAB`
systemarray=(${SYSTEMLINE})
systemtype=${systemarray[1]}
systemmount=${systemarray[2]}

echo "FSTAB: $FSTAB"
echo "SYSTEMNUMBER: $SYSTEMNUMBER"
echo "SYSTEMLINE: $SYSTEMLINE"
echo "systemarray: $systemarray"
#echo "$systemtype"
echo "systemmount: $systemmount"

#rm -r $OUT/*recovery*

if [ ! -f "$UPDATER" ]
then
    make updater &>> /dev/null
fi
if [ ! -f "${ANDROID_HOST_OUT}/framework/signapk.jar" ]
then
    make signapk &>> /dev/null
fi

# Make the updater-script
UPDATER_DIR=$ZIP_DIR/META-INF/com/google/android
mkdir -p $UPDATER_DIR
cp $OUT/obj/EXECUTABLES/updater_intermediates/updater $UPDATER_DIR/update-binary
echo 'ui_print("Installing Devil Recovery...");' > $UPDATER_DIR/updater-script
if [ "$partition_type" = "mtd" ]
then
    echo 'package_extract_file("recovery.img", "/tmp/recovery.img");' >> $UPDATER_DIR/updater-script
    echo "write_raw_image("'"/tmp/recovery.img"'", "'"'$recoverypartition'"'");" >> $UPDATER_DIR/updater-script
elif [ "$partition_type" = "emmc" ]
then
    echo "package_extract_file("'"recovery.img"'", "'"'$recoverypartition'"'");" >> $UPDATER_DIR/updater-script
elif [ "$partition_type" = "bml" ]
then
    echo 'assert(package_extract_file("recovery.img", "/tmp/recovery.img")' >> $UPDATER_DIR/updater-script
    echo "       write_raw_image("'"/tmp/recovery.img"'", "'"'$recoverypartition'"'")" >> $UPDATER_DIR/updater-script
    echo '       delete("/tmp/recovery.img"));' >> $UPDATER_DIR/updater-script
fi
echo "mount("'"'$systemtype'"'", "'"EMMC"'", "'"'$systemmount'"'", "'"system"'");" >> $UPDATER_DIR/updater-script
echo 'package_extract_dir("system", "/system");' >> $UPDATER_DIR/updater-script
echo 'unmount("/system");' >> $UPDATER_DIR/updater-script
echo 'ui_print(" ");' >> $UPDATER_DIR/updater-script
echo 'ui_print("Done!");' >> $UPDATER_DIR/updater-script

# Copy the recovery
cp $OUT/recovery.img $ZIP_DIR/recovery.img

#zip package
cd $ZIP_DIR
zip -qr ../$RECOVERY_VERSION.zip ./
cd $OUT
rm -rf $ZIP_DIR

#sign package
java -jar ${ANDROID_HOST_OUT}/framework/signapk.jar ${SOURCE}/build/target/product/security/testkey.x509.pem ${SOURCE}/build/target/product/security/testkey.pk8 $RECOVERY_VERSION.zip $RECOVERY_VERSION-signed.zip
rm ./$RECOVERY_VERSION.zip
md5sum $RECOVERY_VERSION-signed.zip
cd $SOURCE
